//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kazik.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditLogs
    {
        public int LogID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string Action { get; set; }
        public Nullable<System.DateTime> ActionDate { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
